apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
  namespace: development
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: validationapp
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50