apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: validationapp-volume-claim
  namespace: development
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi