apiVersion: v1
kind: PersistentVolume
metadata:
  name: validationapp-volume
  namespace: development
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/private/tmp/data"