apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: validationapp
  name: validationapp
  namespace: development
spec:
  replicas: 3
  selector:
    matchLabels:
      app: validationapp
  template:
    metadata:
      labels:
        app: validationapp
    spec:
      containers:
      - image: frunzahincu/validation_app
        name: validation-app
