apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: validationapp
  name: validationapp
  namespace: development
spec:
  replicas: 3
  selector:
    matchLabels:
      app: validationapp
  template:
    metadata:
      labels:
        app: validationapp
    spec:
      containers:
      - image: frunzahincu/validation_app
        name: validation-app
        readinessProbe:
          httpGet:
            path: /
            port: 5555
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 5555
          initialDelaySeconds: 10
          periodSeconds: 5
